### ISSUE TITLE
Pine Creek Bug

### ISSUE THREAD

**Issue by MinnickBridger** [grantbaker/Baker_CSCI2270_FinalProject#1]
When doing a targeted storm, I selected Pine Creek and then it showed Flow Increase: seg fault and then quit. Also when I selected to adjust the city consumption, I selected Pine Creek and then it printed the menu repeatedly and broke. Also breaks if I try to adjust Pine Creek's Seasonal scaling, so I think something is wrong with the flow station Pine Creek.

**Comment by grantbaker** [comment]
Fixed. Was an issue with reading user input. Thanks!

**Comment by MinnickBridger** [comment]
I actually fixed that bug for my contribution and added a getline to the
user input and after I pushed my changes I saw that you had fixed it!
Awesome project, Im not sure if I should do something else on a different
project or what but I emailed Rhonda to see what she thinks. Thanks!!

Best,

_Bridger Minnick_
University of Colorado, Boulder
(720)-219-9037
